function renderReport() {
  const d = STATE.stress;
  if (!d) return;

  document.getElementById('report-empty').classList.add('hidden');
  document.getElementById('report-ready').classList.remove('hidden');

  const stressHours = d.phi.filter(v => v >= d.threshold);
  const stressCount = stressHours.length;
  const peakIdx     = d.phi.indexOf(Math.max(...d.phi));
  const peakTime    = new Date(d.times[peakIdx]).toLocaleString('en-GB', {
    month: 'short', day: 'numeric', hour: '2-digit', minute: '2-digit',
  });

  const negHours  = d.prices.filter(p => p < 0).length;
  const highHours = d.prices.filter(p => p > 100).length;
  const total     = d.prices.length;

  const severity = stressCount === 0 ? 'LOW'
    : stressCount <= 2  ? 'LOW'
    : stressCount <= 6  ? 'MEDIUM'
    : stressCount <= 12 ? 'HIGH' : 'CRITICAL';

  let driver = 'Market conditions';
  if (STATE.gen?.series) {
    const wind   = STATE.gen.series['Wind Onshore']?.reduce((a,b) => a+b, 0) || 0;
    const solar  = STATE.gen.series['Solar']?.reduce((a,b) => a+b, 0) || 0;
    const gas    = STATE.gen.series['Fossil Gas']?.reduce((a,b) => a+b, 0) || 0;
    const maxG   = Math.max(wind, solar, gas);
    if      (maxG === gas && gas > wind && gas > solar) driver = 'High fossil gas generation';
    else if (wind < solar * 0.5 && wind < gas * 0.5)   driver = 'Low wind generation';
    else if (solar > wind * 1.5)                        driver = 'High solar generation (price suppression)';
  }

  document.getElementById('report-preview').innerHTML = `
    <div class="report-header">
      <h1>EnergyStress Risk Report</h1>
      <div class="report-meta">
        ${STATE.country} · ${STATE.start} – ${STATE.end} · Generated ${new Date().toLocaleDateString('en-GB')}
      </div>
    </div>

    <div class="report-section">
      <h2>Executive Summary</h2>
      <div class="stat-grid">
        <div class="stat-item">
          <div class="stat-val">${stressCount}</div>
          <div class="stat-lbl">Stress hours</div>
        </div>
        <div class="stat-item">
          <div class="stat-val">${d.max_phi}</div>
          <div class="stat-lbl">Peak kEUR/h</div>
        </div>
        <div class="stat-item">
          <div class="stat-val">${d.avg_price}</div>
          <div class="stat-lbl">Avg EUR/MWh</div>
        </div>
      </div>
      <p style="margin-bottom:8px"><strong>Severity:</strong> <span class="severity-badge severity-${severity}">${severity}</span></p>
      <p style="margin-bottom:4px"><strong>Peak system cost:</strong> ${d.max_phi} kEUR/h on ${peakTime}</p>
      <p><strong>Primary driver:</strong> ${driver}</p>
    </div>

    <div class="report-section">
      <h2>Price Statistics</h2>
      <div class="stat-grid">
        <div class="stat-item">
          <div class="stat-val">${d.min_price}</div>
          <div class="stat-lbl">Min EUR/MWh</div>
        </div>
        <div class="stat-item">
          <div class="stat-val">${Math.max(...d.prices).toFixed(1)}</div>
          <div class="stat-lbl">Max EUR/MWh</div>
        </div>
        <div class="stat-item">
          <div class="stat-val">${d.avg_price}</div>
          <div class="stat-lbl">Avg EUR/MWh</div>
        </div>
      </div>
      <p style="font-size:12px;color:var(--text-muted)">
        ${negHours} of ${total} hours had negative prices (renewable surplus) ·
        ${highHours} hours above 100 EUR/MWh
      </p>
    </div>

    <div class="report-section">
      <h2>Stress Hours Detected</h2>
      ${stressCount === 0
        ? '<p style="color:var(--text-muted);font-size:13px">No stress hours detected in this period.</p>'
        : `<table>
            <thead><tr><th>Time</th><th>Phi (kEUR/h)</th><th>Price (EUR/MWh)</th><th>Load (GW)</th></tr></thead>
            <tbody>
              ${d.times
                .map((t, i) => ({ t, phi: d.phi[i], price: d.prices[i], load: d.load[i] }))
                .filter(r => r.phi >= d.threshold)
                .sort((a, b) => b.phi - a.phi)
                .slice(0, 10)
                .map(r => `<tr>
                  <td>${new Date(r.t).toLocaleString('en-GB',{month:'short',day:'numeric',hour:'2-digit',minute:'2-digit'})}</td>
                  <td style="color:var(--orange);font-weight:700">${r.phi.toFixed(0)}</td>
                  <td>${r.price.toFixed(2)}</td>
                  <td>${r.load.toFixed(2)}</td>
                </tr>`).join('')}
            </tbody>
          </table>`
      }
    </div>

    <div style="margin-top:32px;padding-top:12px;border-top:1px solid var(--border);font-size:10px;color:var(--text-muted)">
      Generated by EnergyStress · Data source: ENTSO-E Transparency Platform · ${new Date().toISOString()}
    </div>`;
}

function downloadReport() {
  const el = document.getElementById('report-preview');
  const opt = {
    margin:       [10, 10, 10, 10],
    filename:     `energystress-report-${STATE.country}-${STATE.start}.pdf`,
    image:        { type: 'jpeg', quality: 0.98 },
    html2canvas:  { scale: 2, useCORS: true },
    jsPDF:        { unit: 'mm', format: 'a4', orientation: 'portrait' },
  };
  html2pdf().set(opt).from(el).save();
}
